//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceServer.Api.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cos420dbEntities : DbContext
    {
        public cos420dbEntities()
            : base("name=cos420dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<criterion> criteria { get; set; }
        public DbSet<interest> interests { get; set; }
        public DbSet<organization> organizations { get; set; }
        public DbSet<reward> rewards { get; set; }
        public DbSet<rewards_has_User_Profile> rewards_has_User_Profile { get; set; }
        public DbSet<transaction> transactions { get; set; }
        public DbSet<vote> votes { get; set; }
        public DbSet<trivia> trivias { get; set; }
        public DbSet<triviapoint> triviapoints { get; set; }
        public DbSet<organization_has_votes> organization_has_votes { get; set; }
        public DbSet<point> points { get; set; }
        public DbSet<User_Profile> User_Profile { get; set; }
    }
}
