//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceServer.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class criterion
    {
        public criterion()
        {
            this.rewards = new HashSet<reward>();
        }
    
        public int id { get; set; }
        public Nullable<int> points { get; set; }
    
        public virtual ICollection<reward> rewards { get; set; }
    }
}
