//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceServer.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class interest
    {
        public interest()
        {
            this.organizations = new HashSet<organization>();
        }
    
        public int id { get; set; }
        public string desc { get; set; }
    
        public virtual ICollection<organization> organizations { get; set; }
    }
}
