//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceServer.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_has_votes
    {
        public int organization_id { get; set; }
        public int votes_id { get; set; }
    }
}
