//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceServer.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class triviapoint
    {
        public int id { get; set; }
        public Nullable<double> Points { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> qsid { get; set; }
    
        public virtual trivia trivia { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
