//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceServer.Api.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        public User_Profile()
        {
            this.points = new HashSet<point>();
            this.rewards_has_User_Profile = new HashSet<rewards_has_User_Profile>();
            this.transactions = new HashSet<transaction>();
            this.triviapoints = new HashSet<triviapoint>();
            this.votes = new HashSet<vote>();
        }
    
        public int uid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string mobileNo { get; set; }
        public string zipCode { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public byte[] pic { get; set; }
    
        public virtual ICollection<point> points { get; set; }
        public virtual ICollection<rewards_has_User_Profile> rewards_has_User_Profile { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
        public virtual ICollection<triviapoint> triviapoints { get; set; }
        public virtual ICollection<vote> votes { get; set; }
    }
}
